# Generated by Django 6.0.2 on 2026-02-12 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_alter_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('Chef', 'Chef'), ('Helper', 'Helper'), ('Delivery', 'Delivery'), ('Manager', 'Manager')], max_length=20)),
                ('contact', models.CharField(max_length=10)),
                ('dob', models.DateField(blank=True, null=True)),
                ('joining_date', models.DateField()),
                ('salary_type', models.CharField(choices=[('Daily', 'Daily'), ('Monthly', 'Monthly')], max_length=10)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=10)),
            ],
        ),
    ]
