# Generated by Django 6.0.2 on 2026-02-12 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_branch_alter_user_user_type_user_branch_cashbook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='App.branch'),
        ),
    ]
