# Generated by Django 6.0.2 on 2026-02-12 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_alter_supplier_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='branch',
        ),
    ]
