# Generated by Django 6.0.2 on 2026-02-13 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_staff'),
        ('App', '0010_remove_product_branch_remove_supplier_branch'),
    ]

    operations = [
    ]
