# Generated by Django 6.0.2 on 2026-02-13 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_merge_20260213_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Yoghurt - NFPC', 'Yoghurt - NFPC'), ('Grocery', 'Grocery'), ('Gas', 'Gas'), ('Vegetables', 'Vegetables'), ('Friday - Atta', 'Friday - Atta'), ('Pepsi / Cola', 'Pepsi / Cola'), ('Plastic', 'Plastic'), ('Meat & Chicken - Coral', 'Meat & Chicken - Coral'), ('Mutton / Paya / Liver', 'Mutton / Paya / Liver'), ('Porotta', 'Porotta'), ('Noodles', 'Noodles'), ('Jalebi', 'Jalebi'), ('Paneer', 'Paneer'), ('Water', 'Water'), ('Fish', 'Fish'), ('Rainbow Milk', 'Rainbow Milk'), ('Sweets - Gulab Jamun', 'Sweets - Gulab Jamun'), ('Bakery - Biscuits', 'Bakery - Biscuits'), ('Charcoal', 'Charcoal'), ('Grease Trap', 'Grease Trap'), ('Pest Control', 'Pest Control'), ('Petrol Bike 1', 'Petrol Bike 1'), ('Petrol Bike 2', 'Petrol Bike 2'), ('Misc Exp 1', 'Misc Exp 1'), ('Misc Exp 2', 'Misc Exp 2')], max_length=100),
        ),
    ]
