# Generated by Django 6.0.2 on 2026-02-13 06:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_alter_expense_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Yoghurt - NFPC', 'Yoghurt - NFPC'), ('Grocery', 'Grocery'), ('Gas', 'Gas'), ('Vegetables', 'Vegetables'), ('Friday - Atta', 'Friday - Atta'), ('Pepsi / Cola', 'Pepsi / Cola'), ('Plastic', 'Plastic'), ('Meat & Chicken - Coral', 'Meat & Chicken - Coral'), ('Mutton / Paya / Liver', 'Mutton / Paya / Liver'), ('Porotta', 'Porotta'), ('Noodles', 'Noodles'), ('Jalebi', 'Jalebi'), ('Paneer', 'Paneer'), ('Water', 'Water'), ('Fish', 'Fish'), ('Rainbow Milk', 'Rainbow Milk'), ('Sweets - Gulab Jamun', 'Sweets - Gulab Jamun'), ('Bakery - Biscuits', 'Bakery - Biscuits'), ('Charcoal', 'Charcoal'), ('Grease Trap', 'Grease Trap'), ('Pest Control', 'Pest Control'), ('Petrol Bike 1', 'Petrol Bike 1'), ('Petrol Bike 2', 'Petrol Bike 2'), ('Misc Exp 1', 'Misc Exp 1'), ('Misc Exp 2', 'Misc Exp 2'), ('Grocery & Inventory', 'Grocery & Inventory'), ('Utilities', 'Utilities'), ('Rent', 'Rent'), ('Salaries', 'Salaries'), ('Miscellaneous', 'Miscellaneous')], max_length=100),
        ),
        migrations.AlterField(
            model_name='expense',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
