# Generated by Django 6.0.2 on 2026-02-13 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_staff_gender_alter_staff_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_staff', to=settings.AUTH_USER_MODEL),
        ),
    ]
