# Generated by Django 6.0.2 on 2026-02-13 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_alter_expense_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='amount_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
