# Generated by Django 6.0.2 on 2026-02-14 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_staff_created_by'),
        ('App', '0015_expense_amount_text'),
    ]

    operations = [
    ]
