# Generated by Django 6.0.2 on 2026-02-14 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0016_merge_0014_staff_created_by_0015_expense_amount_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('breakfast', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('lunch', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('dinner', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('delivery', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cash_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.branch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
