# Generated by Django 6.0.2 on 2026-02-14 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0017_dailysale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailysale',
            old_name='pos',
            new_name='pos_amount',
        ),
        migrations.AddField(
            model_name='dailysale',
            name='pos_type',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card')], default='Cash', max_length=10),
        ),
    ]
