# Generated by Django 6.0.2 on 2026-02-14 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0018_rename_pos_dailysale_pos_amount_dailysale_pos_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysale',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.branch'),
        ),
    ]
