# Generated by Django 6.0.2 on 2026-02-14 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0019_alter_dailysale_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashbook',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
