# Generated by Django 6.0.2 on 2026-02-16 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0020_alter_cashbook_opening_balance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashbook',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='cashbook',
            name='cash_sales',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='cashbook',
            name='closing_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterUniqueTogether(
            name='cashbook',
            unique_together={('branch', 'date')},
        ),
    ]
