# Generated by Django 6.0.2 on 2026-02-16 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0021_alter_cashbook_options_cashbook_cash_sales_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbook',
            name='expenses',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
