# Generated by Django 6.0.2 on 2026-02-17 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0023_deliveryplatform_dailysale_breakfast_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysaleitem',
            name='item_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
