# Generated by Django 6.0.2 on 2026-02-17 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0024_alter_dailysaleitem_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverysale',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
