# Generated by Django 6.0.2 on 2026-02-17 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0025_alter_deliverysale_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysaleitem',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
