# Generated by Django 6.0.2 on 2026-02-18 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0027_salary_salaryadvance'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverysale',
            name='staff',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'Delivery'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.staff'),
        ),
    ]
