# Generated by Django 6.0.2 on 2026-02-20 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0027_salary_salaryadvance'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.manager'),
        ),
    ]
