# Generated by Django 6.0.2 on 2026-02-18 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0028_deliverysale_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverysale',
            name='order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
