# Generated by Django 6.0.2 on 2026-02-25 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0030_alter_deliverysale_order_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_host', models.CharField(default='smtp.gmail.com', max_length=100)),
                ('email_port', models.IntegerField(default=587)),
                ('email_host_user', models.EmailField(max_length=254)),
                ('email_host_password', models.CharField(max_length=200)),
                ('use_tls', models.BooleanField(default=True)),
                ('whatsapp_number', models.CharField(max_length=20)),
            ],
        ),
    ]
