# Generated by Django 6.0.2 on 2026-02-25 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0031_communicationsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationsettings',
            name='email_host',
            field=models.CharField(blank=True, default='smtp.gmail.com', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='communicationsettings',
            name='email_host_password',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='communicationsettings',
            name='email_host_user',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='communicationsettings',
            name='email_port',
            field=models.IntegerField(blank=True, default=587, null=True),
        ),
        migrations.AlterField(
            model_name='communicationsettings',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
