# Generated by Django 6.0.2 on 2026-02-25 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0032_alter_communicationsettings_email_host_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communicationsettings',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
