# Generated by Django 6.0.2 on 2026-02-26 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0029_managersalary'),
        ('App', '0033_communicationsettings_is_active'),
    ]

    operations = [
    ]
