# Generated by Django 6.0.2 on 2026-02-27 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0034_merge_20260226_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='phone',
            field=models.CharField(max_length=16),
        ),
    ]
