# Generated by Django 6.0.2 on 2026-02-27 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0035_alter_manager_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='contact',
            field=models.CharField(max_length=16),
        ),
    ]
