# Generated by Django 6.0.2 on 2026-02-28 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0035_user_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='dashboard_profile/')),
            ],
        ),
    ]
