# Generated by Django 6.0.2 on 2026-03-01 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0036_dashboardprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardprofile',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='dashboard_profile/favicon/'),
        ),
    ]
