# Generated by Django 6.0.2 on 2026-02-27 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0036_alter_staff_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(max_length=16),
        ),
    ]
