# Generated by Django 6.0.2 on 2026-02-27 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0037_alter_supplier_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='contact',
            field=models.BigIntegerField(max_length=16, null=True),
        ),
    ]
