# Generated by Django 6.0.2 on 2026-03-02 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0037_dashboardprofile_favicon'),
        ('App', '0038_alter_register_contact'),
    ]

    operations = [
    ]
