# Generated by Django 6.0.2 on 2026-03-04 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0039_merge_20260302_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.branch'),
        ),
    ]
