# Generated by Django 6.0.2 on 2026-03-05 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0040_manager_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='contact',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
