# Generated by Django 6.0.2 on 2026-03-06 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0043_notification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.branch'),
        ),
        migrations.AddField(
            model_name='notification',
            name='created_by_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
