# Generated by Django 6.0.2 on 2026-03-06 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0044_notification_branch_notification_created_by_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='tag',
            field=models.CharField(blank=True, max_length=190),
        ),
    ]
