# Generated by Django 6.0.2 on 2026-02-12 07:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_alter_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'Admin'), (2, 'Manager'), (3, 'Staff')], null=True),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('Grocery & Inventory', 'Grocery & Inventory'), ('Utilities', 'Utilities'), ('Rent', 'Rent'), ('Salaries', 'Salaries'), ('Miscellaneous', 'Miscellaneous')], max_length=100)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('purchase_type', models.CharField(choices=[('Cash', 'Cash'), ('Credit', 'Credit')], max_length=10)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('invoice', models.FileField(upload_to='invoices/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='App.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='App.supplier')),
            ],
        ),
    ]
