# Generated by Django 6.0.2 on 2026-02-12 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_supplier_alter_user_user_type_product_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(0, 'Admin'), (1, 'Manager'), (2, 'Staff')], null=True),
        ),
    ]
