# Generated by Django 6.0.2 on 2026-02-12 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_expense_branch_expense_created_by_expense_is_settled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='App.branch'),
        ),
        migrations.AlterField(
            model_name='product',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='App.branch'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='App.branch'),
        ),
    ]
