# Generated by Django 6.0.2 on 2026-02-12 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_alter_expense_branch_alter_product_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.branch'),
        ),
        migrations.AlterField(
            model_name='product',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.branch'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.branch'),
        ),
    ]
